"""Build-provenance: VERSION parsing, boot logging, /api/health, and the
build_sha stamp on every trade.

The ledger is paisa-exact but was, until now, recording trades from a build we
could not identify. These tests pin the whole chain: deploy writes
backend/VERSION -> the app reads it at import -> every Trade row carries the
commit that produced it.
"""
from __future__ import annotations

import datetime as dt

import pytest
from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session

from app.core import version as ver


# ── VERSION file parsing ────────────────────────────────────────────────────

VERSION_BODY = (
    "commit=2b3356d\n"
    "branch=feat/exec-completeness\n"
    "deployed_at=2026-07-28T04:30:00Z\n"
    "deployed_by=priyanshusaraf@mac\n"
)


def _write(tmp_path, body):
    p = tmp_path / "VERSION"
    p.write_text(body)
    return p


def test_parses_commit_and_metadata(tmp_path):
    info = ver.parse_version_file(_write(tmp_path, VERSION_BODY))
    assert info["commit"] == "2b3356d"
    assert info["branch"] == "feat/exec-completeness"
    assert info["deployed_by"] == "priyanshusaraf@mac"


def test_tolerates_blank_lines_comments_and_whitespace(tmp_path):
    body = "\n# generated by deploy.sh\n  commit = abc1234  \n\nbranch=main\n"
    info = ver.parse_version_file(_write(tmp_path, body))
    assert info["commit"] == "abc1234"
    assert info["branch"] == "main"


def test_dirty_sha_is_preserved_not_normalised(tmp_path):
    """deploy.sh refuses dirty trees, but if a -dirty SHA ever reaches the app
    we record it verbatim rather than silently cleaning it — an untraceable
    build must look untraceable in the ledger."""
    info = ver.parse_version_file(_write(tmp_path, "commit=abc1234-dirty\n"))
    assert info["commit"] == "abc1234-dirty"


def test_missing_file_returns_empty_not_raise(tmp_path):
    assert ver.parse_version_file(tmp_path / "nope") == {}


def test_unparseable_file_returns_empty_not_raise(tmp_path):
    assert ver.parse_version_file(_write(tmp_path, "\x00\x01 garbage no equals\n")) == {}


def test_file_without_commit_key_is_treated_as_unusable(tmp_path):
    assert ver.parse_version_file(_write(tmp_path, "branch=main\n")) == {}


# ── loud failure, never a silent null ───────────────────────────────────────

def test_missing_version_logs_an_error(tmp_path, monkeypatch, caplog):
    monkeypatch.setattr(ver, "_VERSION_PATH", tmp_path / "absent")
    ver.reset_cache()
    with caplog.at_level("ERROR"):
        assert ver.get_build_sha() == ver.UNKNOWN
    assert any("VERSION" in r.message for r in caplog.records), \
        "a missing VERSION must be loud at boot, not a silent null stamp"


def test_unparseable_version_logs_an_error(tmp_path, monkeypatch, caplog):
    monkeypatch.setattr(ver, "_VERSION_PATH", _write(tmp_path, "garbage\n"))
    ver.reset_cache()
    with caplog.at_level("ERROR"):
        assert ver.get_build_sha() == ver.UNKNOWN
    assert any("VERSION" in r.message for r in caplog.records)


def test_unresolvable_build_is_unknown_never_none(tmp_path, monkeypatch):
    """NULL in trades.build_sha means "row predates the column". A running process
    that cannot read its VERSION is a different fact and must not borrow that
    meaning, or "never recorded" and "recorded as unidentifiable" become the same
    query result."""
    monkeypatch.setattr(ver, "_VERSION_PATH", tmp_path / "absent")
    ver.reset_cache()
    assert ver.get_build_sha() is not None
    assert ver.get_build_sha() == "unknown"


def test_unknown_sentinel_cannot_be_mistaken_for_a_sha():
    """A short SHA is lowercase hex; the sentinel must not be parseable as one."""
    with pytest.raises(ValueError):
        int(ver.UNKNOWN, 16)


def test_good_version_does_not_log_an_error(tmp_path, monkeypatch, caplog):
    monkeypatch.setattr(ver, "_VERSION_PATH", _write(tmp_path, VERSION_BODY))
    ver.reset_cache()
    with caplog.at_level("ERROR"):
        assert ver.get_build_sha() == "2b3356d"
    assert not [r for r in caplog.records if "VERSION" in r.message]


def test_read_is_cached_so_every_trade_insert_is_not_a_file_read(tmp_path, monkeypatch):
    p = _write(tmp_path, VERSION_BODY)
    monkeypatch.setattr(ver, "_VERSION_PATH", p)
    ver.reset_cache()
    assert ver.get_build_sha() == "2b3356d"
    p.write_text("commit=deadbee\n")          # changed on disk mid-process
    assert ver.get_build_sha() == "2b3356d"   # still the booted build
    ver.reset_cache()
    assert ver.get_build_sha() == "deadbee"


# ── /api/health exposure ────────────────────────────────────────────────────

def test_health_reports_the_build(monkeypatch, tmp_path):
    from fastapi.testclient import TestClient
    from app.main import app

    monkeypatch.setattr(ver, "_VERSION_PATH", _write(tmp_path, VERSION_BODY))
    ver.reset_cache()
    with TestClient(app) as c:
        body = c.get("/api/health").json()
    assert body["ok"] is True
    assert body["build"]["commit"] == "2b3356d"
    assert body["build"]["branch"] == "feat/exec-completeness"


def test_health_reports_unknown_build_without_failing(monkeypatch, tmp_path):
    from fastapi.testclient import TestClient
    from app.main import app

    monkeypatch.setattr(ver, "_VERSION_PATH", tmp_path / "absent")
    ver.reset_cache()
    with TestClient(app) as c:
        r = c.get("/api/health")
    assert r.status_code == 200          # health must not go red on a missing VERSION
    # Same sentinel the ledger stamps, so health and trades.build_sha can never
    # disagree about what this process is. deploy.sh compares this to the SHA it
    # shipped, and "unknown" fails that comparison — which is the intent.
    assert r.json()["build"]["commit"] == "unknown"


# ── the migration, against a production-shaped DB ───────────────────────────

def _legacy_trades_ddl() -> str:
    """The trades table WITHOUT build_sha — i.e. what production has today."""
    return """
    CREATE TABLE trades (
        id INTEGER NOT NULL PRIMARY KEY,
        instrument_key VARCHAR(32), direction VARCHAR(8), option_type VARCHAR(4),
        tradingsymbol VARCHAR(64), exchange VARCHAR(8), segment VARCHAR(16),
        strategy_key VARCHAR(64), strike FLOAT, expiry DATE, qty INTEGER,
        entry_premium FLOAT, entry_cost FLOAT, entry_spot FLOAT, entry_time DATETIME,
        exit_premium FLOAT, exit_charges FLOAT, exit_spot FLOAT, exit_time DATETIME,
        exit_reason VARCHAR(32), gross_pnl FLOAT, charges_total FLOAT, net_pnl FLOAT,
        return_pct FLOAT, holding_minutes FLOAT, win BOOLEAN, mode VARCHAR(8)
    )
    """


def _cols(conn, table="trades"):
    return {r[1] for r in conn.execute(text(f"PRAGMA table_info({table})"))}


def test_migration_adds_build_sha_to_a_pre_migration_table(tmp_path, monkeypatch):
    """Against a DB shaped like production (34 real trades, no build_sha)."""
    import app.db.session as sess_mod

    db = tmp_path / "legacy.db"
    eng = create_engine(f"sqlite:///{db}")
    with eng.begin() as c:
        c.execute(text(_legacy_trades_ddl()))
        c.execute(text(
            "INSERT INTO trades (id, tradingsymbol, net_pnl, mode) "
            "VALUES (1, 'SUZLON', 417.40, 'live')"))
        assert "build_sha" not in _cols(c)

    monkeypatch.setattr(sess_mod, "engine", eng)
    sess_mod._migrate_schema()

    with eng.begin() as c:
        assert "build_sha" in _cols(c)
        row = c.execute(text("SELECT tradingsymbol, net_pnl, build_sha FROM trades")).one()
    assert row[0] == "SUZLON"          # existing row survives
    assert row[1] == 417.40            # paisa-exact value untouched
    assert row[2] is None              # historic trades are honestly unknown


def test_migration_is_idempotent(tmp_path, monkeypatch):
    """init_db runs on every boot — a second pass must not raise 'duplicate column'."""
    import app.db.session as sess_mod

    eng = create_engine(f"sqlite:///{tmp_path / 'idem.db'}")
    with eng.begin() as c:
        c.execute(text(_legacy_trades_ddl()))
    monkeypatch.setattr(sess_mod, "engine", eng)

    sess_mod._migrate_schema()
    sess_mod._migrate_schema()          # must be a no-op, not an error
    sess_mod._migrate_schema()

    with eng.begin() as c:
        assert "build_sha" in _cols(c)


def test_migration_does_not_touch_a_table_it_has_no_additions_for(tmp_path, monkeypatch):
    """Guard against the ALTER loop running on a table that create_all hasn't made."""
    import app.db.session as sess_mod

    eng = create_engine(f"sqlite:///{tmp_path / 'empty.db'}")
    monkeypatch.setattr(sess_mod, "engine", eng)
    sess_mod._migrate_schema()          # no tables at all — must not raise


def test_build_sha_column_is_nullable():
    from app.db.models import Trade
    assert Trade.__table__.c.build_sha.nullable is True


# ── the stamp itself ────────────────────────────────────────────────────────

def _make_trade(**kw):
    from app.db.models import Trade
    base = dict(
        instrument_key="NIFTY", direction="long", option_type="CE",
        tradingsymbol="NIFTY26JUL24000CE", exchange="NFO", strike=24000.0,
        expiry=dt.date(2026, 7, 30), qty=75,
        entry_premium=100.0, entry_cost=7500.0, entry_spot=24000.0,
        entry_time=dt.datetime(2026, 7, 28, 9, 30),
        exit_premium=160.0, exit_charges=20.0, exit_spot=24100.0,
        exit_time=dt.datetime(2026, 7, 28, 9, 45), exit_reason="TARGET",
        gross_pnl=4500.0, charges_total=20.0, net_pnl=4480.0,
        return_pct=0.6, holding_minutes=15.0, win=True,
    )
    base.update(kw)
    return Trade(**base)


def test_new_trade_is_stamped_with_the_running_build(tmp_path, monkeypatch):
    from app.db.models import Base

    monkeypatch.setattr(ver, "_VERSION_PATH", _write(tmp_path, VERSION_BODY))
    ver.reset_cache()

    eng = create_engine(f"sqlite:///{tmp_path / 'stamp.db'}")
    Base.metadata.create_all(eng)
    with Session(eng) as s:
        s.add(_make_trade())
        s.commit()
        assert s.query(type(_make_trade())).one().build_sha == "2b3356d"


def test_trade_stamp_is_unknown_when_version_is_absent(tmp_path, monkeypatch):
    """No VERSION => 'unknown', never a guess and never NULL.

    NULL is reserved for rows that predate the column. This row was written by a
    live process, so it must say so — the useful query is
    `WHERE build_sha = 'unknown'`, which finds engines that deployed outside
    deploy.sh, and that query is impossible if these rows are NULL."""
    from app.db.models import Base, Trade

    monkeypatch.setattr(ver, "_VERSION_PATH", tmp_path / "absent")
    ver.reset_cache()

    eng = create_engine(f"sqlite:///{tmp_path / 'nostamp.db'}")
    Base.metadata.create_all(eng)
    with Session(eng) as s:
        s.add(_make_trade())
        s.commit()
        assert s.query(Trade).one().build_sha == "unknown"


def test_the_orm_cannot_write_a_null_build_sha(tmp_path, monkeypatch):
    """Passing build_sha=None explicitly still stamps 'unknown'.

    SQLAlchemy treats an explicit None as "not supplied" and applies the column
    default. That is the behaviour we want and it is load-bearing: NULL is
    reserved for rows the *migration* left alone, so no code path that books a
    trade can manufacture one. Pinned because it is surprising — the obvious
    reading of `Trade(build_sha=None)` is that it writes a NULL."""
    from app.db.models import Base, Trade

    monkeypatch.setattr(ver, "_VERSION_PATH", tmp_path / "absent")
    ver.reset_cache()

    eng = create_engine(f"sqlite:///{tmp_path / 'nonull.db'}")
    Base.metadata.create_all(eng)
    with Session(eng) as s:
        s.add(_make_trade(build_sha=None))
        s.commit()
        assert s.query(Trade).one().build_sha == "unknown"


def test_null_and_unknown_are_distinguishable_in_one_table(tmp_path, monkeypatch):
    """The whole point of the sentinel: a pre-migration row and an unidentifiable
    build must be separable by a query, not collapsed onto the same value.

    The NULL row is inserted the way real ones exist — a legacy row that the
    migration added the column to — not via the ORM, which by design cannot
    produce one (see the test above)."""
    import app.db.session as sess_mod
    from app.db.models import Base

    monkeypatch.setattr(ver, "_VERSION_PATH", tmp_path / "absent")
    ver.reset_cache()

    db = tmp_path / "mixed.db"
    eng = create_engine(f"sqlite:///{db}")
    with eng.begin() as c:                      # a production-shaped legacy row
        c.execute(text(_legacy_trades_ddl()))
        c.execute(text("INSERT INTO trades (id, tradingsymbol) VALUES (1, 'SUZLON')"))
    monkeypatch.setattr(sess_mod, "engine", eng)
    sess_mod._migrate_schema()                  # adds build_sha, leaves it NULL
    Base.metadata.create_all(eng)

    with Session(eng) as s:
        s.add(_make_trade(id=2))                        # running, unidentifiable
        s.add(_make_trade(id=3, build_sha="2b3356d"))   # identified
        s.commit()

    with eng.begin() as c:
        pre = c.execute(text("SELECT COUNT(*) FROM trades WHERE build_sha IS NULL")).scalar()
        unk = c.execute(text("SELECT COUNT(*) FROM trades WHERE build_sha = 'unknown'")).scalar()
        known = c.execute(text("SELECT COUNT(*) FROM trades WHERE build_sha = '2b3356d'")).scalar()
    assert (pre, unk, known) == (1, 1, 1)


def test_explicit_build_sha_is_not_overwritten(tmp_path, monkeypatch):
    """Backfill/repair tooling must be able to set it directly."""
    from app.db.models import Base, Trade

    monkeypatch.setattr(ver, "_VERSION_PATH", _write(tmp_path, VERSION_BODY))
    ver.reset_cache()

    eng = create_engine(f"sqlite:///{tmp_path / 'explicit.db'}")
    Base.metadata.create_all(eng)
    with Session(eng) as s:
        s.add(_make_trade(build_sha="0f93f9a"))
        s.commit()
        assert s.query(Trade).one().build_sha == "0f93f9a"


@pytest.fixture(autouse=True)
def _restore_version_cache():
    yield
    ver.reset_cache()
