"""Pure point-in-time Type 3 selectors and analytics descriptions."""
from __future__ import annotations

from app.ir.first_party.logic_state import make_catalogue


TYPE_3_NAMES = tuple(sorted(set("""
AGGRESSOR_BUY_SELL_FLOW ANNUALIZED_BASIS ASK_QUANTITY ATM ATM_PLUS_MINUS_N BASIS
BEST_ASK BEST_BID BID_QUANTITY BOOK_SLOPE CALENDAR_SPREAD CALL_PUT_SELECTOR
CHAIN_OPEN_INTEREST CHANGE_IN_OPEN_INTEREST CONTINUOUS_RESEARCH_SERIES
CUMULATIVE_DELTA CUMULATIVE_N_LEVEL_DEPTH DAYS_TO_EXPIRY DELTA DELTA_TARGET_SELECTOR
DEPTH_IMBALANCE DEPTH_LEVEL_N DEPTH_WEIGHTED_SPREAD DTE_SELECTOR EXPIRY_LIST
FAR_CONTRACT FAR_EXPIRY FRONT_CONTRACT GAMMA IMPLIED_VOLATILITY IV_PERCENTILE
IV_RANK LIQUIDITY_CONCENTRATION MICROPRICE MONEYNESS_SELECTOR NEAREST_EXPIRY
NEXT_CONTRACT NEXT_EXPIRY OPEN_INTEREST_CONCENTRATION OPTION_CHAIN_SLICE
PCR_OPEN_INTEREST PCR_VOLUME PEER_BASKET PROVIDER_TOTAL_BUY_SELL_QUANTITY
PUT_CALL_PARITY_DEVIATION RELATIVE_VALUE_STRUCTURE RHO ROLL_SELECTOR
SECONDARY_INSTRUMENT_INPUT SKEW SPREAD STRADDLE_PRICE STRADDLE_SELECTOR
STRANGLE_SELECTOR STRIKE_VOLUME_OI_RATIO SYNTHETIC_FUTURE TERM_STRUCTURE THETA
TRADABLE_MAPPED_CONTRACT TRADE_IMBALANCE VEGA VOLUME_DELTA WEIGHTED_DEPTH_IMBALANCE
""".split())))
CAPABILITY_GATED_NAMES = tuple(sorted(set("""
AGGRESSOR_BUY_SELL_FLOW ASK_QUANTITY BEST_ASK BEST_BID BID_QUANTITY BOOK_SLOPE
CHAIN_OPEN_INTEREST CHANGE_IN_OPEN_INTEREST CUMULATIVE_DELTA
CUMULATIVE_N_LEVEL_DEPTH DELTA DEPTH_IMBALANCE DEPTH_LEVEL_N
DEPTH_WEIGHTED_SPREAD GAMMA IMPLIED_VOLATILITY IV_PERCENTILE IV_RANK
LIQUIDITY_CONCENTRATION MICROPRICE OPEN_INTEREST_CONCENTRATION PCR_OPEN_INTEREST
PCR_VOLUME PROVIDER_TOTAL_BUY_SELL_QUANTITY RHO SKEW SPREAD
STRIKE_VOLUME_OI_RATIO TERM_STRUCTURE THETA TRADE_IMBALANCE VEGA VOLUME_DELTA
WEIGHTED_DEPTH_IMBALANCE
""".split())))
V2_TYPES, V2_COMPONENTS, V2_IMPLEMENTATIONS, DATA_REQUIREMENTS, NODE_CONTRACTS = make_catalogue(
    TYPE_3_NAMES, "TYPE_3", CAPABILITY_GATED_NAMES,
)


__all__ = [
    "CAPABILITY_GATED_NAMES", "DATA_REQUIREMENTS", "NODE_CONTRACTS", "TYPE_3_NAMES",
    "V2_COMPONENTS", "V2_IMPLEMENTATIONS", "V2_TYPES",
]
