"""Pure Type 1 intent descriptions; this module has no engine or broker imports."""
from __future__ import annotations

from app.ir.first_party.logic_state import make_catalogue


TYPE_1_NAMES = tuple(sorted(set("""
ACCOUNT_EQUITY ADDITIONS_COUNT ADD_ONLY_WHEN_PROFITABLE ADD_POSITION
AGGREGATE_STOP_HANDLING ATR_STOP ATR_TRAIL AVAILABLE_MARGIN AVERAGE_PRICE
BARS_IN_POSITION BREAKEVEN BROKER_RESIDENT_PROTECTION_REQUEST BUY CLOSE_POSITION
DAILY_PNL DEPLOYMENT_PNL DRAWDOWN ENTER_LONG ENTER_SHORT ENTRY_PRICE EXPIRY_EXIT
EXPOSURE FIXED_CAPITAL FIXED_STOP_PERCENT FIXED_UNITS FLATTEN_ACCOUNT
FLATTEN_DEPLOYMENT IOC_VALIDITY LIMIT LOTS MAE MARKET MARKETABLE_LIMIT_POLICY
MAX_ADDITIONS MAX_CAPITAL_CAP MAX_HOLDING_TIME MAX_TOTAL_RISK MFE
MIN_MAX_LOT_CONSTRAINT MULTIPLE_TARGETS PARTIAL_EXIT PERCENT_EQUITY PERCENT_RISK
POINT_STOP QUANTITY REALIZED_PNL REVERSE RISK_REWARD_TARGET SCALE_FIXED
SCALE_PERCENT SELL SESSION_EXIT STOP STOP_DISTANCE_RISK STOP_LIMIT
TAKE_PROFIT_PERCENT TIME_IN_POSITION TRAILING_PERCENT TRAILING_POINTS
UNREALIZED_PNL VOLATILITY_SIZING
""".split())))
CAPABILITY_GATED_NAMES = ("BROKER_RESIDENT_PROTECTION_REQUEST", "IOC_VALIDITY")
V2_TYPES, V2_COMPONENTS, V2_IMPLEMENTATIONS, DATA_REQUIREMENTS, NODE_CONTRACTS = make_catalogue(
    TYPE_1_NAMES, "TYPE_1", CAPABILITY_GATED_NAMES,
)


__all__ = [
    "CAPABILITY_GATED_NAMES", "DATA_REQUIREMENTS", "NODE_CONTRACTS", "TYPE_1_NAMES",
    "V2_COMPONENTS", "V2_IMPLEMENTATIONS", "V2_TYPES",
]
